# Generated by Django 3.2.4 on 2021-08-06 14:31

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210806_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=post.models.upload_to_blog),
        ),
    ]
